version: '2.2'
services:
  react:
    container_name: scraping
    image: node:alpine
    #cpuset: '1'
    #mem_limit: 512m
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
     - PORT=8080
    volumes:
      - $PWD/.npm/:/root/.npm
      - $PWD/:/root/react
    networks:
      - net
    ports:
      - '80:80'
      - '8080:8080'
networks:
  net:
